FROM nginx:1.17.6-alpine
MAINTAINER acarvaja acarvaja@student.42madrid.com

# SSL keys Fueron creadas con el comando:
# openssl req -x509 -nodes -days 365 -newkey rsa:2048 '/C=ES/ST=Aranjuez/L=Madrid/O=42/CN=acarvaja' -keyout nginx.key -out nginx.crt;
COPY nginx.conf /etc/nginx
RUN chown -R nginx:nginx /usr/share/nginx;
COPY index.html /usr/share/nginx/html
RUN mkdir /etc/nginx/ssl
COPY keys/nginx.crt /etc/nginx/ssl
COPY keys/nginx.key /etc/nginx/ssl
RUN chmod 600 /etc/nginx/ssl/nginx.key
RUN chmod 644 /etc/nginx/ssl/nginx.crt

# --- ssh ---
# SSH keys Fueron creadas con el comando:
# ssh-keygen -f lsssh_host_dsa_key -N '' -t dsa;
# ssh-keygen -f ssh_host_rsa_key -N '' -t rsa; 
RUN apk add --no-cache openrc nginx openssh-server; \
	rc-update add sshd; \
	echo "root:password" | chpasswd;
COPY sshd_config /etc/ssh/
COPY keys/ssh_host_dsa_key /etc/ssh/
COPY keys/ssh_host_dsa_key.pub /etc/ssh/
COPY keys/ssh_host_rsa_key /etc/ssh/
COPY keys/ssh_host_rsa_key.pub /etc/ssh/
RUN chmod 600 /etc/ssh/ssh_host_dsa_key
RUN chmod 644 /etc/ssh/ssh_host_dsa_key.pub
RUN chmod 600 /etc/ssh/ssh_host_rsa_key
RUN chmod 644 /etc/ssh/ssh_host_rsa_key.pub

# --- telegraf ---
ENV TELEGRAF_VERSION 1.13.1
COPY telegraf.tar.gz .
COPY telegraf.conf /etc/telegraf/
RUN tar -C . -xzf telegraf.tar.gz; \
	chmod +x telegraf/*; \
	mv /telegraf/usr/bin/telegraf /usr/bin/; \
	rm -rf *.tar.gz telegraf/

#Eliminando logs viejos de NGINX (access.log es usado por telegraf)
RUN rm /var/log/nginx/access.log; \
	touch /var/log/nginx/access.log;

# --- puesta en marcha del script ---
COPY nginx.sh /usr/local/bin
RUN chmod +x ./usr/local/bin/nginx.sh

EXPOSE 80 443 32022
ENTRYPOINT ["./usr/local/bin/nginx.sh"]

CMD ["tail", "-F", "/var/log/nginx/access.log"]